spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8080
zuul:
  routes:
    mall:
      path: /mall/**
      serviceId: secondkill
nacos:
  config:
    server-addr: localhost:8848